package com.example.assigmentweek4

const val MOVIE_TITLE_KEY = "MOVIE_TITLE_KEY"
const val MOVIE_POSTER_KEY = "MOVIE_POSTER_KEY"
const val MOVIE_DES_KEY = "MOVIE_DES_KEY"
const val MOVIE_VOTE_KEY ="MOVIE_VOTE_KEY"
const val MOVIE_BACKDROP_KEY = "MOVIE_BACKDROP_KEY"
const val MOVIE_VIDEO_KEY ="MOVIE_VIDEO_KEY"
const val MOVIE_DATE_KEY = "MOVIE_DATE_KEY "